{% set name = "curl-impersonate" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/lexiforest/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  - sha256: be2494020a26378ceb888c2198e3cc1b8dee1150e58e5f432aa3bb92659d8e17
    patches:
     - patches/0001-unix-makefile-fix.patch  # [unix]
     - patches/0002-windows-unvendor.path  # [win]
  # https://github.com/lexiforest/curl-impersonate/blob/v1.2.0/.github/workflows/build-win.yaml#L20-L25
  - git_url: https://github.com/google/brotli              # [win]
    git_rev: ed738e842d2fbdf2d6459e39267a633c4a9b2f5d      # [win]
    folder: deps/brotli                                    # [win]
  - git_url: https://boringssl.googlesource.com/boringssl  # [win]
    git_rev: 673e61fc215b178a90c0e67858bbf162c8158993      # [win]
    folder: deps/boringssl                                 # [win]
  - git_url: https://github.com/curl/curl                  # [win]
    git_rev: curl-8_15_0                                   # [win]
    folder: deps/curl                                      # [win]
  - git_url: https://github.com/nghttp2/nghttp2            # [win]
    git_rev: 8f44147c385fb1ed93a6f39911eeb30279bfd2dd      # [win]
    folder: deps/nghttp2                                   # [win]
  - git_url: https://github.com/ngtcp2/nghttp3             # [win]
    git_rev: v1.9.0                                        # [win]
    folder: deps/nghttp3                                   # [win]
  - git_url: https://github.com/ngtcp2/ngtcp2              # [win]
    git_rev: v1.11.0                                       # [win]
    folder: deps/ngtcp2                                    # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("curl-impersonate", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
    - msys2-patch  # [win]
    # https://github.com/lexiforest/curl-impersonate/blob/v1.2.0/win/build.bat#L22
    - clang  # [win]
    - nasm  # [win]
    - make  # [unix]
    - libtool  # [unix]
    - automake  # [unix]
    - autoconf  # [unix]
    - pkg-config  # [unix]
    - unzip  # [unix]
    - zlib {{ zlib }}
    - zstd {{ zstd }}
  host:
    - zlib
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/libcurl-impersonate.4.dylib  # [osx]
    - test -f $PREFIX/lib/libcurl-impersonate.so.4  # [linux]
    - test -f $PREFIX/lib/libcurl-impersonate.so.4.8.0  # [linux]
    - test -f $PREFIX/lib/libcurl-impersonate.a  # [unix]
    - test -f $PREFIX/lib/libcurl-impersonate{{ SHLIB_EXT }}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\libcurl_imp.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libcurl.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\curl_chrome100.bat exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\curl\\curl.h exit 1  # [win]

about:
  home: https://github.com/lexiforest/curl-impersonate
  summary: A special build of curl that can impersonate the four major browsers Chrome, Edge, Safari and Firefox.
  description: |
    A special build of curl that can impersonate the four major browsers Chrome, Edge, Safari and Firefox.
    curl-impersonate is able to perform TLS and HTTP handshakes that are identical to that of a real browser.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/lexiforest/curl-impersonate
  doc_url: https://github.com/lexiforest/curl-impersonate/blob/main/README.md

extra:
  skip-lints:
    - patch_unnecessary